package ch.quazz.caverna.score;

public enum Token {
    DWARFS, DWELLINGS, DOGS, SHEEP, DONKEYS, BOARS, CATTLE, GRAINS, VEGETABLES, RUBIES, GOLD, BEGGING_MARKERS,
    SMALL_PASTURES, LARGE_PASTURES, ORE_MINES, RUBY_MINES, UNUSED_SPACE, STONE, ORE, WEAPONS, ADJACENT_DWELLINGS
}
